# Generated by Django 5.1.4 on 2025-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_App', '0002_brand_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
