# Generated by Django 5.1.4 on 2025-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_App', '0005_user_ship_address_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='total_price',
            field=models.FloatField(null=True),
        ),
    ]
