# Generated by Django 5.1.4 on 2025-01-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_App', '0006_alter_bookings_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='delivery',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='sub_total',
            field=models.FloatField(null=True),
        ),
    ]
