# Generated by Django 5.1.4 on 2025-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_App', '0007_alter_bookings_delivery_alter_bookings_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
