# Generated by Django 5.1.4 on 2025-01-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Global_App', '0010_multi_bookings_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, null=True)),
                ('service_slug', models.CharField(max_length=100, null=True)),
                ('service_image', models.ImageField(null=True, upload_to='Service/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
